const express=require('express');const cors=require('cors');const crypto=require('crypto');const fs=require('fs');const path=require('path');const app=express();app.use(cors());app.use(express.json());const PORT=process.env.PORT||8080;const ADMIN_IDENTITY=process.env.ADMIN_IDENTITY||'rafael';const ADMIN_PIN=process.env.ADMIN_PIN||'246810';const ADMIN_NAME=process.env.ADMIN_NAME||'Rafael';const DATA_FILE=process.env.DATA_FILE||path.join(__dirname,'data.json');let db={clients:[],drivers:[],trips:[],payments:[],settings:{monthlyFeeCup:1000,transfermovilCard:''},sessions:{}};try{if(fs.existsSync(DATA_FILE))db={...db,...JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))};}catch(e){}function save(){try{fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2));}catch(e){}}function id(){return crypto.randomUUID();}function token(){return crypto.randomBytes(24).toString('hex');}function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer /,'');const s=db.sessions[t];if(!s)return res.status(401).json({error:'unauthorized'});req.session=s;next();}function admin(req,res,next){auth(req,res,()=>req.session.role==='admin'?next():res.status(403).json({error:'forbidden'}));}
app.get('/health',(q,r)=>r.json({ok:true,service:'rafael-movil-api'}));app.get('/ready',(q,r)=>r.json({ok:true}));
app.post('/v1/auth/admin',(q,r)=>{if(String(q.body.identity)!==ADMIN_IDENTITY||String(q.body.pin)!==ADMIN_PIN)return r.status(401).json({error:'invalid_credentials'});const t=token();db.sessions[t]={role:'admin',identity:ADMIN_IDENTITY,name:ADMIN_NAME};save();r.json({token:t,role:'admin',name:ADMIN_NAME});});
app.post('/v1/auth/register',(q,r)=>{const role=String(q.body.role||'');const identity=String(q.body.identity||'').trim(),name=String(q.body.name||'').trim();if(!['client','driver'].includes(role)||!identity||!name)return r.status(400).json({error:'bad_request'});const list=role==='client'?db.clients:db.drivers;let u=list.find(x=>x.identity===identity);if(!u){u={id:id(),identity,name,vehicle:q.body.vehicle||'Auto',active:true,paidUntil:null};list.push(u);}else{u.name=name;if(q.body.vehicle)u.vehicle=q.body.vehicle;}const t=token();db.sessions[t]={role,identity,name};save();r.json({token:t,role,user:u});});
app.post('/v1/auth/login',(q,r)=>{const role=String(q.body.role||''),identity=String(q.body.identity||'');const list=role==='client'?db.clients:db.drivers;const u=list.find(x=>x.identity===identity);if(!u)return r.status(404).json({error:'not_found'});const t=token();db.sessions[t]={role,identity,name:u.name};save();r.json({token:t,role,user:u});});
app.get('/v1/me',auth,(q,r)=>{const list=q.session.role==='client'?db.clients:db.drivers;const u=list.find(x=>x.identity===q.session.identity)||{};r.json({...q.session,...u});});
app.post('/v1/logout',auth,(q,r)=>{const t=(q.headers.authorization||'').replace(/^Bearer /,'');delete db.sessions[t];save();r.json({ok:true});});
app.get('/v1/settings',auth,(q,r)=>r.json(db.settings));app.put('/v1/settings',admin,(q,r)=>{if(Number(q.body.monthlyFeeCup)>0)db.settings.monthlyFeeCup=Number(q.body.monthlyFeeCup);if(q.body.transfermovilCard!==undefined)db.settings.transfermovilCard=String(q.body.transfermovilCard);save();r.json(db.settings);});
app.post('/v1/trips',auth,(q,r)=>{if(q.session.role!=='client')return r.status(403).json({error:'forbidden'});const t={id:id(),clientId:q.session.identity,origin:String(q.body.origin||''),destination:String(q.body.destination||''),vehicle:String(q.body.vehicle||'Auto'),offer:Number(q.body.offer||0),counterOffer:null,driverId:'',status:'searching',createdAt:new Date().toISOString()};db.trips.push(t);save();r.status(201).json(t);});
app.get('/v1/trips/inbox',auth,(q,r)=>{if(q.session.role!=='driver')return r.status(403).json({error:'forbidden'});r.json(db.trips.filter(t=>['searching','countered'].includes(t.status)||t.driverId===q.session.identity));});
app.post('/v1/trips/:id/accept',auth,(q,r)=>{const t=db.trips.find(x=>x.id===q.params.id);if(!t)return r.status(404).json({error:'not_found'});t.driverId=q.session.identity;t.status='assigned';save();r.json(t);});
app.post('/v1/trips/:id/counter',auth,(q,r)=>{const t=db.trips.find(x=>x.id===q.params.id);if(!t)return r.status(404).json({error:'not_found'});t.counterOffer=Number(q.body.counterOffer||q.body.amount||0);t.driverId=q.session.identity;t.status='countered';save();r.json(t);});
app.patch('/v1/trips/:id/status',auth,(q,r)=>{const t=db.trips.find(x=>x.id===q.params.id);if(!t)return r.status(404).json({error:'not_found'});t.status=String(q.body.status||t.status);save();r.json(t);});
app.get('/v1/admin/dashboard',admin,(q,r)=>r.json({clients:db.clients.length,drivers:db.drivers.length,trips:db.trips.length,activeTrips:db.trips.filter(t=>!['completed','cancelled'].includes(t.status)).length,pendingPayments:db.payments.filter(p=>p.status==='pending').length,grossCup:db.trips.filter(t=>t.status==='completed').reduce((a,t)=>a+(t.counterOffer||t.offer||0),0)}));
app.get('/v1/admin/clients',admin,(q,r)=>r.json(db.clients));app.get('/v1/admin/drivers',admin,(q,r)=>r.json(db.drivers));app.get('/v1/admin/trips',admin,(q,r)=>r.json(db.trips));
app.listen(PORT,'0.0.0.0',()=>console.log('Rafael Movil API on '+PORT));