import 'dart:convert';
import 'package:flutter/material.dart';
import '../services/rest_backend_service.dart';
class AdminClientsPanel extends StatefulWidget{const AdminClientsPanel({super.key,required this.backend});final RestRafaelBackend backend;@override State<AdminClientsPanel> createState()=>_AdminClientsPanelState();}
class _AdminClientsPanelState extends State<AdminClientsPanel>{List<Map<String,dynamic>> clients=const[];bool loading=false;String? error;final search=TextEditingController();@override void initState(){super.initState();_load();}@override void dispose(){search.dispose();super.dispose();}
Future<void> _load()async{if(loading)return;setState(()=>loading=true);try{final rows=await widget.backend.adminClients(query:search.text);if(mounted)setState((){clients=rows;error=null;});}catch(_){if(mounted)setState(()=>error='No se pudieron cargar los clientes.');}finally{if(mounted)setState(()=>loading=false);}}
Future<void> _active(String id,bool active)async{try{await widget.backend.setClientActive(id,active);await _load();}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('No se pudo cambiar la cuenta.')));}}
Widget _avatar(Map<String,dynamic>u){final url=u['photoUrl']?.toString()??'';ImageProvider<Object>? image;if(url.startsWith('http')){image=NetworkImage(url);}else if(url.startsWith('data:image')){image=MemoryImage(base64Decode(url.split(',').last));}return CircleAvatar(radius:26,backgroundImage:image,child:image==null?const Icon(Icons.person,size:29):null);}
@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
Row(children:[const Expanded(child:Text('Clientes',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),IconButton(onPressed:loading?null:_load,icon:const Icon(Icons.refresh))]),const Text('Datos privados visibles solamente para Rafael.'),const SizedBox(height:8),
TextField(controller:search,onSubmitted:(_)=>_load(),decoration:InputDecoration(labelText:'Buscar cliente',hintText:'Nombre o carnet',prefixIcon:const Icon(Icons.search),suffixIcon:IconButton(onPressed:_load,icon:const Icon(Icons.arrow_forward)))),if(loading)const LinearProgressIndicator(),if(error!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text(error!)),if(!loading&&clients.isEmpty)const Padding(padding:EdgeInsets.all(12),child:Text('No hay clientes para mostrar.')),
...clients.map((u){final active=u['active']!=false;final id=u['id']?.toString()??'';return Card(margin:const EdgeInsets.symmetric(vertical:5),child:ListTile(leading:_avatar(u),title:Text(u['name']?.toString()??'Cliente',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('Carnet: ${u['identity']??'-'}\n${u['trips']??0} viajes · ${active?'Cuenta activa':'Cuenta bloqueada'}'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v){if(v=='toggle')_active(id,!active);},itemBuilder:(_)=>[PopupMenuItem<String>(value:'toggle',child:Text(active?'Bloquear cuenta':'Reactivar cuenta'))])));}),
])));}
